stages:
  - build
  - deploy

build veebiprojekt-frontend:
  stage: build
  only:
    refs:
      - master
  tags:
    - frontend-runner
  script:
    - docker build -t veebiprojekt-frontend .

deploy veebiprojekt-frontend:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - frontend-runner
  script:
    - cd /opt/web-project/frontend
    - docker-compose down
    - docker-compose up -d
